.PHONY: clean All

All:
	@echo "----------Building project:[ Section11-Challenge - Debug ]----------"
	@cd "Section11-Challenge" && "$(MAKE)" -f  "Section11-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section11-Challenge - Debug ]----------"
	@cd "Section11-Challenge" && "$(MAKE)" -f  "Section11-Challenge.mk" clean
